### ISSUE TITLE
Create an Externalized Object response on the server side

### ISSUE THREAD

**Issue by cy-polo** [jadbalout/node-amf#3]
Hello,

I would like to be able to reply to the client with a response containing an `Externalized Object`, but I can't.

Can you please tell me how to do it? I looked in the source code but I didn't understand.
Thank you in advance for your answer!

What I want to do:
![image](https://user-images.githubusercontent.com/50364607/187220461-85f3d3bd-8904-4a5b-8522-b9c6759da058.png)

What's happening right now:
![image](https://user-images.githubusercontent.com/50364607/187220864-3694e2d2-8e64-4de3-9d91-6127b2813f90.png)

What I do:

```js
class AMFAppSettingsService extends Service {
    constructor() {
        super("MovieStarPlanet.WebService.AppSettings.AMFAppSettingsService");
    }

    GetAppSettings(packet) {
        console.log(packet.bodies[0].data);

        // how node-amf can know it's a Externalized Object?

        packet.respond([ /* big array here */ ]);
    }
}
```

Thank you in advance for your help!

**Comment by jadbalout** [comment]
Hello! Sorry for the delayed response. Please update to the latest version 1.1.9 and see the example below:

```js
const { TypedObjects } = require('@jadbalout/nodeamf');
const externalizedObject = new TypedObjects.ArrayCollection([ /* array here */]);
```

**Comment by cy-polo** [comment]
No problem, thanks for the answer!
I'll try it soon.

Have a nice day!
